# -*- coding: utf-8 -*-
"""Linear regression .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JLPBd2Co7G87k8wNIOW87f-zbaOogFaV
"""

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("/content/Dataset-28-2-Linear-Regression-work-salary.csv")
df

from sklearn.model_selection import train_test_split
X = df.drop("Salary", axis=1)
y = df['Salary']

X_train,X_test,y_train,y_test= train_test_split(X,y, test_size = 0.2,\
                                                   random_state=112)

from sklearn.linear_model import LinearRegression
my_model = LinearRegression() 
  
result = my_model.fit(X_train, y_train)

predictions = result.predict(X_test) 
predictions

plt.scatter(X_train, y_train, color ='c') 
plt.plot(X_test, predictions, color ='b')

from sklearn.metrics import r2_score
r2_score(y_test,predictions)

pred_new=result.predict([[55]]) 
pred_new